### PR TITLE
Feature/bac 1165

### PR DESCRIPTION
**Pull request by connorpacala**
Added 'Headers' field to guide and documented use of 'X-Field' header for filtering data.

### CODE REVIEW

**Comment by iamzjk** [comment]
`select` is not in headers, maybe it is better to call this document `partial object fetching`.
Should we also add request example for `select` usage? It is an important usage too

**Comment by connorpacala** [comment]
Ah, that link to 'select' was supposed to go to the Data endpoint guide where it is already documented.

**Comment by connorpacala** [comment]
I guess the question is, do we want a headers section that details the x-field use or a data filtering section that the Data 'select' parameter links to that details x-field header and select parameter use?

**Comment by iamzjk** [comment]
I think it is better to focus on use cases. like `how do you do partial fetching` instead of `what can you do with headers`

**Comment by connorpacala** [comment]
Ok, changing that now. What do you think about calling it Data Filtering instead of Partial Object Fetching?

**Comment by iamzjk** [comment]
data filtering sounds like filtering the rows, eg. where temp > 30
what about column filtering or field filtering?

**Comment by connorpacala** [comment]
I like column filtering. Field filtering sounds weird to me

**Pull request merged**
